apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: task-manager-api
data:
  APP_ENV: "dev"
  AUTH_ENABLED: "true"
  JWT_ALGORITHM: "RS256"
  KEYCLOAK_ISSUER: "http://83.69.249.206/realms/devsecops"
  KEYCLOAK_CLIENT_ID: "task-manager-api"
  KEYCLOAK_AUDIENCE: "account"
  KEYCLOAK_JWKS_URL: "http://keycloak-svc.task-manager-api.svc.cluster.local/realms/devsecops/protocol/openid-connect/certs"
  CORS_ALLOW_ORIGINS: "http://83.69.249.206"