apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: task-manager-api
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://task_user:task_password@postgres-svc:5432/task_manager"
