#   kubectl create secret tls keycloak-tls-secret \
#     -n task-manager-api \
#     --cert=infra/tls/keycloak.crt \
#     --key=infra/tls/keycloak.key
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls-secret
  namespace: task-manager-api
type: kubernetes.io/tls
data:
  tls.crt: "<base64-encoded-certificate>"
  tls.key: "<base64-encoded-private-key>"
