apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: task-manager-api
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "changeme"
  KC_DB_USERNAME: "task_user"
  KC_DB_PASSWORD: "changeme"
